volunteer-service:
  replicas: 1
  namespace: volunteer-service
  image: 585534523398.dkr.ecr.us-east-1.amazonaws.com/volunteer-service:development-58484f4
  imagePullPolicy: IfNotPresent
  port: 8083
  imagePullSecrets:
    - name: ecr-secret
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "250m"
      memory: "384Mi"
  probes:
    enabled: true
    path: /health
    startup:
      failureThreshold: 180
      periodSeconds: 1
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 180
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
  envFrom:
    - secretRef:
        name: region-config
    - secretRef:
        name: volunteer-dynamodb-config
  env_vars: volunteer_db
  ingress:
    path: /volunteer-service(/|$)(.*)
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
